### ISSUE TITLE
When are files committed?

### ISSUE THREAD

**Issue by eshellman** [gutenbergbooks/786#1]
Looking at the december processing history of this title I see that it was submitted and publiished 3 tiimes. The first two submissions are not reflected in the repo - critical errors were reported, and it looks like the first 2 attempts were wiped before the before the fixed files were put in the repo. Is the repo involved in the submission process, or is the repo meant as an ex post facto document? If the repo IS involved why were the first two submissions wiped, thus negating the archival value of the repo?

**Comment by nfenwick** [comment]
I think the history is there--just not all in the repo. The original book was posted in March of 2013.  You can find that version in the 1/2/3 filesystem under https://www.gutenberg.org/files/786/old/. There was a rework in 2019. You can find those file in "old" also. Finally, errata processing was done with the Errata Workbench, which creates a repository. That's why you see an initial commit of two weeks ago. Note that any future work will be based off the repository, not the 1/2/3 files, so version track will start to occur.

**Comment by eshellman** [comment]
I don't think that's correct. the 786 repository was created three times. Errata workbench seems to be creating reposiories over and over again. It shouldn't do that, and its users should not be able to make it do that.

Also, I think that when a repository is made for a backkfile book, the initial commit should push all the old files. That way the history is in one place.

Is there documentation somewhere?

Eric

**Comment by eshellman** [comment]
BTW, I've had to deal with this in my monthly conversion review. It would REALLY help me do that if I could see the corrections that are made.

For example, this month I found an issue with Ebookmaker:
https://github.com/gutenbergtools/ebookmaker/issues/210￼
<u> element not allowed in epub · Issue #210 · gutenbergtools/ebookmaker
github.com

**Comment by nfenwick** [comment]
"Errata workbench seems to be creating reposiories over and over again. It shouldn't do that, and its users should not be able to make it do that." Agreed. If it's doing that, it's an error. I'll chase it down.

**Comment by nfenwick** [comment]
"Also, I think that when a repository is made for a backkfile book, the initial commit should push all the old files. That way the history is in one place."
Greg doesn't want non-public domain content in the repository. That includes what we checkpoint into "old" when the repositories are created via the Errata Workbench.

**Comment by nfenwick** [comment]
"Is there documentation somewhere?"

http://pglaf.org/~rfrank/errata/errata.htm

**Comment by eshellman** [comment]
wait, what is in the files directory that is not public???

**Comment by nfenwick** [comment]
I consider the public domain content of a book to be what was originally published, with the possible addition of a Transcriber's Note or notes. That should not change. 
What I do **not** consider in the public domain is the PG legal boilerplate and the metadata. The boilerplate can, and likely will, change. 
The idea is that the repository contains the original book; everything else is added based on the current legal boilerplate and the current code for displaying the metadata.

**Comment by eshellman** [comment]
The metadata is in the public domain as it is not subject to copyright, if copyright is the issue. But copyright is disclaimed in license.txt.

Styling and formatting by DPers IS copyrightable, except for the copyright disclaimer in license.txt

Boilerplate has to be public in order to have force. And you have more boilerplate!

And why it that more important than recording the changes?

**Comment by nfenwick** [comment]
My task was to have the repository contain what the author wrote, which is how it's implemented. I agree with that design goal. Changing the design would be a Greg discussion.

**Comment by gbnewby** [comment]
Roger's characterization of the use of github is correct. We want to track changes in the posted content. We do not want to track changes in headers, footers or metadata. Those are applied programmatically.

The approach of applying headers, footers & metadata programmatically to generated files was a major impetus behind the current approach of pushing files without those items. We need to push files with a sentinel line due to limitations in the processing that happens on ibiblio. Otherwise, new publications and errata publications are to be born without headers, footers and metadata. 

Errata handling is one of the most complex jobs in the PG universe. Having the content in github serves the purposes of more precisely tracking changes, opens the possibility of simpler workflows for errata processing, and exposes the collection in a way that will let people use PRs and forks to submit changes. 

Eric wrote, "Styling and formatting by DPers IS copyrightable, except for the copyright disclaimer in license.txt." No, that is a pre-Feist notion. Sweat of the brow is not authorship. See the "no sweat of the brow copyright" how-to at www.gutenberg.org

**Comment by eshellman** [comment]
On Jan 7, 2024, at 11:47 AM, Greg Newby ***@***.***> wrote:
> 
> 
> Roger's characterization of the use of github is correct. We want to track changes in the posted content. We do not want to track changes in headers, footers or metadata. Those are applied programmatically.
> 
> The approach of applying headers, footers & metadata programmatically to generated files was a major impetus behind the current approach of pushing files without those items. We need to push files with a sentinel line due to limitations in the processing that happens on ibiblio. Otherwise, new publications and errata publications are to be born without headers, footers and metadata.
> 
> Errata handling is one of the most complex jobs in the PG universe. Having the content in github serves the purposes of more precisely tracking changes, opens the possibility of simpler workflows for errata processing, and exposes the collection in a way that will let people use PRs and forks to submit changes.
> 
100% agree with that; what I was worried about was the erasure of history, which you keep telling me has been an longtime emphasis of PR.
> Eric wrote, "Styling and formatting by DPers IS copyrightable, except for the copyright disclaimer in license.txt." No, that is a pre-Feist notion. Sweat of the brow is not authorship. See the "no sweat of the brow copyright" how-to at www.gutenberg.org <http://www.gutenberg.org/>
The large CSS stylesheets frequently used in PG books are clearly not "sweat-of-the-brow". The holding in Feist  was, accoring to the copyright office, that

a work of authorship must possess “some minimal degree of creativity” to sustain a copyright claim. Feist, 499 U.S. at 358, 362 (citation omitted). “[T]he requisite level of creativity is extremely low.” Even a “slight amount” of creative expression will suffice. “The vast majority of works make the grade quite easily, as they possess some creative spark, ‘no matter how crude, humble or obvious it might be.’” Id. at 346 (citation omitted). 

Eric

**Comment by eshellman** [comment]
Wow that's so complicated!

I was surprised that there's no usage of git or the github workflow. What am I missing?

**Comment by nfenwick** [comment]
Members of the errata team have a wide range of technical ability which doesn't always include knowing how to use Git commands.

**Comment by eshellman** [comment]
*I* hardly know how to use git commands! What I meant was, if it's all under the hood, does the errata team need know about it?
Is the errata workbench *using* git or GitHib flow for anything? (yet)?

**Comment by nfenwick** [comment]
If they use the errata workbench and the eBook they choose has a GitHub repository, then it uses the repository files. There is a new commit for their work. It's much easier for them to use the Workbench starting with the GitHub files. If there is no repository, it uses the latest 1/2/3 files and, in the errata process, creates a new GitHub repository.

**Comment by eshellman** [comment]
As I'm unfamiliar with the older process, I don't quite understand why it's much easier to start with GitHub files.

From the usage I'm seeing they don't have to use the GitHub files, right?

**Comment by nfenwick** [comment]
correct
